# Generated by Django 3.0.6 on 2020-06-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True, verbose_name='Identificador'),
        ),
    ]
