# Generated by Django 3.0.6 on 2020-06-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_thread_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default=None, max_length=100, verbose_name='Identificador'),
        ),
    ]
