# Generated by Django 3.0.6 on 2020-06-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200613_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True, verbose_name='Identificador'),
        ),
    ]
